### ISSUE TITLE
Add to melpa?

### ISSUE THREAD

**Issue by jbr** [mrkkrp/nushell-mode#3]
I just came here from [awesome-nu#editor-extensions](https://github.com/nushell/awesome-nu#editor-extensions) and was excited to see that there's a nu major mode for emacs now! I am setting up `straight-use-package` for the first time in order to use this, but imagine there are probably people who would prefer to install from melpa. I've added a package to melpa before and it was [fairly straightforward](https://github.com/melpa/melpa/blob/master/README.md). Would it make sense to publish this package to melpa?

Thanks!

**Comment by azzamsa** [comment]
Hi.

I switched back to ZSH after many issues I faced in NuShell. Mainly https://github.com/nushell/nushell/issues/6339.
Currently, I don't plan to switch back to  NuShell again. It is okay for you to take ownership of this package.

**Comment by mrkkrp** [comment]
Hey @azzamsa, I'd like to take over and maintain this package. I've been maintaining some Emacs Lisp code for years: https://github.com/mrkkrp?tab=repositories&q=&type=&language=emacs+lisp&sort=stargazers. If you agree, how should we proceed about it?

**Comment by azzamsa** [comment]
> If you agree, how should we proceed about it?

100 %. I will provide any action necessary.

**Comment by mrkkrp** [comment]
:tada: I guess the next logical step is to [transfer the repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-personal-account) to my account.

**Comment by azzamsa** [comment]
@mrkkrp done.

**Comment by mrkkrp** [comment]
@azzamsa, Hmm, strange,  I haven't received any notification about this. Are you sure you used the right handle? I know people often make mistakes in mine. Could you perhaps check?

**Comment by azzamsa** [comment]
I have re-transfer the ownership to your handle.

**Comment by mrkkrp** [comment]
Strange, I still haven't received anything :man_shrugging:

**Comment by azzamsa** [comment]
I have tried both `mrkkrp` and `@mrkkrp`. However, it doesn't have pop-up selection as if we add more contributor to the repo.

![image](https://github.com/azzamsa/emacs-nushell/assets/17734314/1ba96008-823a-4ce4-89f4-3ed232c67c2d)

**Comment by mrkkrp** [comment]
Yeah, pretty weird. Maybe it is something we could report to GitHub (I will try to do that in the coming days). Looks like a bug to me.

**Comment by mrkkrp** [comment]
@azzamsa I contacted GitHub about this and they suggested enabling notification both via the web-interface and via email. I did that. Can you please try again?

**Comment by azzamsa** [comment]
Should I use `@` or not? 
Context https://github.com/azzamsa/emacs-nushell/issues/3#issuecomment-1560132923

**Comment by mrkkrp** [comment]
I think it should work without it.

**Comment by azzamsa** [comment]
![image](https://github.com/azzamsa/emacs-nushell/assets/17734314/b43d1d46-df92-4671-9dc9-1e3109479251)

**Comment by mrkkrp** [comment]
I've got another reply from GitHub. They looked a bit more into it and I think they fixed the problem. Can you try one last time? Really sorry for this long sequence of attempts!

**Comment by azzamsa** [comment]
![image](https://github.com/azzamsa/emacs-nushell/assets/17734314/cac3b103-aa0d-4824-be73-55e5e15fadc2)

**Comment by mrkkrp** [comment]
It worked! Thanks for not giving up :-)

**Comment by azzamsa** [comment]
@mrkkrp would you like to share what's happening? is it a GitHub bug?

**Comment by mrkkrp** [comment]
It turned out that if you opt out of email notifications then the request won't be sent to your email and it won't show up in the web interface either. So, I had to enable email notifications, but even then it at first defaulted to an email address I haven't used in 8 years instead of my primary email. I consider the fact that opting out of email notifications prevents any kind of notifications about repository transfers a bug.

**Comment by azzamsa** [comment]
Same here. I never use any email notifications for the app I open every day, including Github.
If someone would like to transfer a repository to me, I need to activate my email notification first.

**Comment by mrkkrp** [comment]
The package is now on MELPA.
