### ISSUE TITLE
Symbol's definition is void: nushell-indent-line

### ISSUE THREAD

**Issue by jbr** [mrkkrp/nushell-mode#4]
It seems like `indent-line-function` [is set to](https://github.com/azzamsa/emacs-nushell/blob/master/nushell-mode.el#L586) `'nushell-indent-line'` but that doesn't exist. Is there a definition of that somewhere?

**Comment by dschrempf** [comment]
Same here. Is this mode still developed?

**Comment by jbr** [comment]
@dschrempf See https://github.com/azzamsa/emacs-nushell/issues/3#issuecomment-1488321385 — it looks like this repo is unmaintained

**Comment by dschrempf** [comment]
I see, thank you. I am just starting with `nushell`, and I do not know how far I get, so feel free to take the lead!

**Comment by dschrempf** [comment]
FYI, I created a fork that has this issue fixed: https://github.com/dschrempf/emacs-nushell/tree/indent-line-fix.

At the moment however, I do not want to take over the package.

**Comment by mrkkrp** [comment]
Resolved in 2b1e15526f2c67f4321a692cbeb0e7c4bf138f8f by adopting @dschrempf's solution. This is a temporary measure though, because we will need to define a correct `nushell-indent-line` later.
